//导航相关配置
export default [
    {
        title:'首页',
        url:'/dashboard',
        onlyAdmin:false,
    },
    {
        title:'图书管理',
        url:'/books',
        onlyAdmin:false,
    },
    {
        title:'用户管理',
        url:'/user',
        onlyAdmin:true, 
    },
    {
        title:'操作日志',
        url:'/log',
        onlyAdmin:true,
    },
    {
        title:'其他管理',
        onlyAdmin:true,
        children:[
            {
                title:'图书分类管理',
                url:'/book-classify',
                onlyAdmin:true,
            },
            {
                title:'重置密码管理',
                url:'/reset/password',
                onlyAdmin:true,
            },
            {
                title:'邀请码管理',
                url:'/invite-code',
                onlyAdmin:true,
            },
        ],
    },
    {
        title:'修改密码',
        url:'/profile',
        onlyAdmin:false,
    },
];